---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-233-427d0f2ba518> in <module>()
      1 # Split S into development set (I) and evaluation set (J)
----> 2 IJ = em.split_train_test(G2, train_proportion=0.6, random_state=0)
      3 #I = IJ['train']
      4 #J = IJ['test']
      5 #print(len(I[I['gold']==1]))

/anaconda2/lib/python2.7/site-packages/py_entitymatching/matcher/matcherutils.pyc in split_train_test(labeled_data, train_proportion, random_state, verbose)
     75         cm.get_metadata_for_candset(
     76             labeled_data,
---> 77             logger, verbose)
     78 
     79     # # Validate metadata

/anaconda2/lib/python2.7/site-packages/py_entitymatching/catalog/catalog_manager.pyc in get_metadata_for_candset(candset, lgr, verbose)
   1296     fk_rtable = get_fk_rtable(candset)
   1297     # # Get the base tables
-> 1298     ltable = get_ltable(candset)
   1299     rtable = get_rtable(candset)
   1300     # Get the base table keys

/anaconda2/lib/python2.7/site-packages/py_entitymatching/catalog/catalog_manager.pyc in get_ltable(candset)
   1336     """
   1337     # Return the ltable for a candidate set. This function is just a sugar
-> 1338     return get_property(candset, 'ltable')
   1339 
   1340 

/anaconda2/lib/python2.7/site-packages/py_entitymatching/catalog/catalog_manager.pyc in get_property(data_frame, property_name)
     71         raise KeyError(
     72             'Requested metadata ( %s ) for the given DataFrame is not '
---> 73             'present in the catalog' % property_name)
     74 
     75     # Return the requested property for the input DataFrame

KeyError: 'Requested metadata ( ltable ) for the given DataFrame is not present in the catalog'